import { useEffect, useRef, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { useQuery } from "@tanstack/react-query";
import { Mic, MicOff, Video, VideoOff, MonitorUp, PhoneOff } from "lucide-react";
import { useTranslation } from "react-i18next";
import { getMeeting, joinMeeting, leaveMeeting, endMeeting, startMeeting } from "../../services/api/meetings.api.js";
import { createMeetingSocket } from "../../lib/socket.js";
import { useAuth } from "../../hooks/useAuth.js";

export default function MeetingPage() {
  const { meetingId } = useParams(); const { token, user } = useAuth(); const navigate = useNavigate(); const { t } = useTranslation();
  const localRef = useRef(null); const remoteRef = useRef(null); const pcRef = useRef(null); const streamRef = useRef(null); const socketRef = useRef(null); const remoteUserRef = useRef(null);
  const [joined, setJoined] = useState(false); const [ready, setReady] = useState(false); const [peerPresent, setPeerPresent] = useState(false); const [elapsed, setElapsed] = useState(0); const [muted, setMuted] = useState(false); const [cameraOff, setCameraOff] = useState(false); const [sharing, setSharing] = useState(false); const [status, setStatus] = useState("connecting"); const [error, setError] = useState("");
  const { data, isLoading } = useQuery({ queryKey: ["meeting", meetingId], queryFn: () => getMeeting(meetingId, token), enabled: !!token }); const meeting = data?.data;
  useEffect(() => { if (!meeting || joined || !ready) return undefined; let disposed = false;
    (async () => { try { if (!navigator.mediaDevices?.getUserMedia || !window.RTCPeerConnection) throw new Error("unsupported"); let media; let cameraUnavailable = false; try { media = await navigator.mediaDevices.getUserMedia({ audio: true, video: true }); } catch (mediaError) { if (["NotReadableError", "NotFoundError", "OverconstrainedError"].includes(mediaError?.name)) { cameraUnavailable = true; media = await navigator.mediaDevices.getUserMedia({ audio: true, video: false }); } else throw mediaError; } if (disposed) return; if (cameraUnavailable) setError(t("meetings.cameraBusy")); streamRef.current = media; if (localRef.current) localRef.current.srcObject = media; const join = await joinMeeting(meetingId, token); const socket = createMeetingSocket(token); socketRef.current = socket; const pc = new RTCPeerConnection({ iceServers: join.data?.ice_servers || [] }); pcRef.current = pc; media.getTracks().forEach((track) => pc.addTrack(track, media)); pc.ontrack = (e) => { setPeerPresent(true); if (remoteRef.current) remoteRef.current.srcObject = e.streams[0]; }; pc.onicecandidate = (e) => { if (e.candidate && remoteUserRef.current) socket.emit("webrtc:ice-candidate", { targetUserId: remoteUserRef.current, candidate: e.candidate }); }; pc.onconnectionstatechange = () => { setStatus(pc.connectionState === "connected" ? "connected" : pc.connectionState === "failed" ? "reconnecting" : pc.connectionState); if (["disconnected", "failed", "closed"].includes(pc.connectionState)) setPeerPresent(false); }; socket.on("meeting:started", () => setStatus("active")); socket.on("meeting:ended", () => { setStatus("ended"); setPeerPresent(false); }); socket.on("meeting:participant-joined", async ({ userId }) => { setPeerPresent(true); remoteUserRef.current = userId; if (String(join.data?.role) === "host") { const offer = await pc.createOffer(); await pc.setLocalDescription(offer); socket.emit("webrtc:offer", { targetUserId: userId, offer }); } }); socket.on("meeting:participant-left", () => { setPeerPresent(false); if (remoteRef.current) remoteRef.current.srcObject = null; }); socket.on("webrtc:offer", async ({ fromUserId, offer }) => { remoteUserRef.current = fromUserId; await pc.setRemoteDescription(offer); const answer = await pc.createAnswer(); await pc.setLocalDescription(answer); socket.emit("webrtc:answer", { targetUserId: fromUserId, answer }); }); socket.on("webrtc:answer", ({ answer }) => pc.setRemoteDescription(answer)); socket.on("webrtc:ice-candidate", ({ candidate }) => pc.addIceCandidate(candidate)); socket.on("connect", () => { setStatus("connected"); socket.emit("meeting:join", { room_id: join.data.room_id }); }); socket.on("disconnect", () => setStatus("reconnecting")); socket.connect(); setJoined(true); setStatus("waiting"); } catch (e) { setError(e.message === "unsupported" ? t("meetings.unsupported") : t("meetings.permission")); } })();
    return () => { disposed = true; socketRef.current?.disconnect(); pcRef.current?.close(); streamRef.current?.getTracks().forEach((track) => track.stop()); };
  }, [meeting, meetingId, token, t, ready]);
  const toggle = (kind) => { const track = streamRef.current?.getTracks().find((t) => t.kind === kind); if (!track) return; track.enabled = !track.enabled; if (kind === "audio") setMuted(!track.enabled); else setCameraOff(!track.enabled); socketRef.current?.emit(track.enabled ? `meeting:${kind === "audio" ? "unmute" : "camera-on"}` : `meeting:${kind === "audio" ? "mute" : "camera-off"}`); };
  const share = async () => { try { if (!sharing) { const display = await navigator.mediaDevices.getDisplayMedia({ video: true }); const sender = pcRef.current?.getSenders().find((s) => s.track?.kind === "video"); if (sender) sender.replaceTrack(display.getVideoTracks()[0]); display.getVideoTracks()[0].onended = () => setSharing(false); setSharing(true); } else { const camera = streamRef.current?.getVideoTracks()[0]; const sender = pcRef.current?.getSenders().find((s) => s.track?.kind === "video"); if (sender && camera) sender.replaceTrack(camera); setSharing(false); } } catch {} };
  const isHost = Boolean(meeting && String(user?.id || user?._id) === String(meeting.host_user_id?._id || meeting.host_user_id));
  useEffect(() => { if (!joined) return undefined; const timer = window.setInterval(() => setElapsed((value) => value + 1), 1000); return () => window.clearInterval(timer); }, [joined]);
  const start = async () => { try { await startMeeting(meetingId, token); setStatus("active"); } catch (e) { setError(e.message); } };
  const leave = async (finish = false) => { try { await (finish ? endMeeting : leaveMeeting)(meetingId, token); } finally { navigate("/contracts"); } };
  if (isLoading) return <div className="grid min-h-screen place-items-center bg-ink text-slate">{t("common.loading")}</div>;
  if (!meeting) return <div className="grid min-h-screen place-items-center bg-ink text-slate">{t("errors.MEETING_NOT_FOUND")}</div>;
  if (["ended", "cancelled"].includes(meeting.status)) return <div className="grid min-h-screen place-items-center bg-ink p-6 text-center text-slate"><div><h1 className="font-display text-2xl">{meeting.title}</h1><p className="mt-2 text-slate-300">This meeting is {meeting.status} and cannot be joined.</p><button type="button" onClick={() => navigate("/meetings")} className="mt-5 rounded bg-brass px-4 py-2 font-semibold text-ink">Back to meetings</button></div></div>;
  if (!ready) return <div className="mx-auto grid min-h-screen max-w-lg place-items-center bg-ink p-6 text-slate"><section className="w-full rounded-card border border-ink-300 bg-ink-50 p-6"><p className="text-xs text-slate-300">NexusWork</p><h1 className="mt-2 font-display text-2xl">{meeting.title}</h1><p className="mt-2 text-sm text-slate-300">Check your camera and microphone before joining.</p>{error && <div role="alert" className="mt-4 rounded border border-brick p-3 text-sm">{error}</div>}<div className="mt-5 flex gap-3"><button type="button" onClick={() => setCameraOff((v) => !v)} className="rounded border border-ink-300 px-3 py-2 text-sm">{cameraOff ? t("meetings.camera") : t("meetings.cameraOff")}</button><button type="button" onClick={() => setMuted((v) => !v)} className="rounded border border-ink-300 px-3 py-2 text-sm">{muted ? t("meetings.microphone") : t("meetings.muted")}</button></div><button type="button" onClick={() => setReady(true)} className="mt-6 w-full rounded bg-brass px-4 py-3 font-semibold text-ink">{t("meetings.join")}</button></section></div>;
  return <div className="min-h-screen bg-ink-900 p-4 text-slate"><header className="mb-4 flex items-center justify-between"><div><p className="text-xs text-slate-300">NexusWork · {status === "reconnecting" ? t("meetings.reconnecting") : status} · {String(Math.floor(elapsed / 60)).padStart(2, "0")}:{String(elapsed % 60).padStart(2, "0")}</p><h1 className="font-display text-xl">{meeting.title}</h1><p className="text-xs text-slate-300">{peerPresent ? "Participant connected" : "Waiting for the other participant…"}</p></div><div className="flex gap-2">{isHost && meeting.status === "waiting" && <button onClick={start} className="rounded bg-brass px-3 py-2 text-sm text-ink">Start meeting</button>}<button onClick={() => navigate("/chat")} className="rounded bg-ink-50 px-3 py-2 text-sm">Chat</button><button onClick={() => leave(false)} className="rounded bg-ink-50 px-3 py-2 text-sm" aria-label={t("meetings.leave")}><PhoneOff className="mr-2 inline h-4 w-4" />{t("meetings.leave")}</button>{isHost && <button onClick={() => leave(true)} className="rounded bg-brick px-3 py-2 text-sm" aria-label={t("meetings.end")}>{t("meetings.end")}</button>}</div></header>{error && <div role="alert" className="mb-4 rounded border border-brick p-3 text-sm">{error}</div>}<main className="grid gap-4 md:grid-cols-[minmax(0,1fr)_240px]"><div className="grid gap-4 md:grid-cols-2"><div className="relative"><video ref={localRef} autoPlay muted playsInline className="aspect-video w-full rounded-card bg-black object-cover" /><span className="absolute bottom-3 left-3 rounded bg-black/60 px-2 py-1 text-xs">You</span></div><div className="relative"><video ref={remoteRef} autoPlay playsInline className="aspect-video w-full rounded-card bg-black object-cover" />{!peerPresent && <span className="absolute inset-0 grid place-items-center text-sm text-slate-300">Waiting for participant…</span>}</div></div><aside className="rounded-card border border-ink-300 bg-ink-50 p-4"><h2 className="font-semibold">Participants</h2><div className="mt-3 space-y-2 text-sm"><p className="rounded bg-ink-700 px-3 py-2">You · {isHost ? "Host" : "Participant"}</p><p className="rounded bg-ink-700 px-3 py-2">{peerPresent ? "Contract partner · Connected" : "Contract partner · Not connected"}</p></div><button type="button" onClick={() => navigate("/chat")} className="mt-4 w-full rounded border border-ink-300 px-3 py-2 text-sm">Open contract chat</button></aside></main><footer className="mt-4 flex justify-center gap-3"><button onClick={() => toggle("audio")} className="rounded-full bg-ink-50 p-3" aria-label={t("meetings.microphone")}>{muted ? <MicOff /> : <Mic />}</button><button onClick={() => toggle("video")} className="rounded-full bg-ink-50 p-3" aria-label={t("meetings.camera")}>{cameraOff ? <VideoOff /> : <Video />}</button><button onClick={share} className="rounded-full bg-ink-50 p-3" aria-label={sharing ? t("meetings.stopSharing") : t("meetings.shareScreen")}><MonitorUp /></button></footer></div>;
}
