import PDFDocument from "pdfkit";

function formatMoney(amount, currency = "usd") {
  const value = (Math.round((amount ?? 0) * 100) / 100).toFixed(2);
  return `${currency.toUpperCase()} ${value}`;
}

function formatDate(date) {
  if (!date) return "—";
  return new Date(date).toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });
}

// Renders an invoice as a PDF and returns it as a Buffer.
export function renderInvoicePdf(invoice) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: "A4", margin: 50 });
    const chunks = [];
    doc.on("data", (chunk) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    const currency = invoice.currency || "usd";

    doc
      .fontSize(20)
      .fillColor("#1a1a1a")
      .text("NexusWork", { continued: false })
      .fontSize(10)
      .fillColor("#666666")
      .text("Invoice");

    doc.moveDown(1.5);

    doc.fontSize(14).fillColor("#1a1a1a").text(`Invoice ${invoice.invoice_number}`);
    doc.fontSize(10).fillColor("#666666");
    doc.text(`Status: ${invoice.status}`);
    doc.text(`Issued: ${formatDate(invoice.createdAt)}`);
    if (invoice.due_date) doc.text(`Due: ${formatDate(invoice.due_date)}`);
    if (invoice.paid_at) doc.text(`Paid: ${formatDate(invoice.paid_at)}`);
    if (invoice.contract_id?.terms?.title) doc.text(`Project: ${invoice.contract_id.terms.title}`);

    doc.moveDown(1);

    const colStart = doc.x;
    const colWidth = 250;
    doc.fontSize(10).fillColor("#1a1a1a");
    doc.text("Billed to (client)", colStart, doc.y, { width: colWidth, continued: false });
    doc.fillColor("#666666").text(invoice.client_id?.name || "—", colStart, doc.y);
    if (invoice.client_id?.email) doc.text(invoice.client_id.email, colStart, doc.y);

    const rightColY = doc.y;
    doc.fillColor("#1a1a1a").text("Paid to (student)", colStart + colWidth, rightColY - (invoice.client_id?.email ? 28 : 14), {
      width: colWidth,
    });
    doc.fillColor("#666666").text(invoice.student_id?.name || "—", colStart + colWidth);
    if (invoice.student_id?.email) doc.text(invoice.student_id.email, colStart + colWidth);

    doc.moveDown(2);

    // Line items table
    const tableTop = doc.y;
    const cols = { desc: colStart, qty: 330, price: 390, total: 460 };
    doc.fontSize(10).fillColor("#1a1a1a");
    doc.text("Description", cols.desc, tableTop);
    doc.text("Qty", cols.qty, tableTop);
    doc.text("Unit price", cols.price, tableTop);
    doc.text("Total", cols.total, tableTop);
    doc
      .moveTo(colStart, tableTop + 15)
      .lineTo(510, tableTop + 15)
      .strokeColor("#dddddd")
      .stroke();

    let y = tableTop + 22;
    doc.fillColor("#333333");
    for (const item of invoice.line_items || []) {
      const qty = item.quantity ?? 1;
      const lineTotal = qty * (item.unit_price ?? 0);
      doc.text(item.description, cols.desc, y, { width: 270 });
      doc.text(String(qty), cols.qty, y);
      doc.text(formatMoney(item.unit_price, currency), cols.price, y);
      doc.text(formatMoney(lineTotal, currency), cols.total, y);
      y += 20;
    }

    doc
      .moveTo(colStart, y + 4)
      .lineTo(510, y + 4)
      .strokeColor("#dddddd")
      .stroke();

    doc
      .fontSize(12)
      .fillColor("#1a1a1a")
      .text("Total", cols.price, y + 14)
      .text(formatMoney(invoice.amount, currency), cols.total, y + 14);

    doc
      .fontSize(8)
      .fillColor("#999999")
      .text("Generated by NexusWork. This document is a record of a milestone payment made through the platform.", colStart, 760, {
        width: 460,
      });

    doc.end();
  });
}