import i18n from "i18next";
import { initReactI18next } from "react-i18next";
import en from "./locales/en.json";
import am from "./locales/am.json";
import af from "./locales/af.json";
import { translateLegacyDom } from "./legacy.js";

const supported = ["en", "am", "af"];
const sharedResources = {
  en: { common: { mainNavigation: "Main", openMenu: "Open menu", mobileNavigation: "Mobile", menu: "Menu", theme: "Theme", searchPages: "Search projects, contracts, pages…", noResults: "No results found.", account: "Account" }, auth: { login: "Log in", signup: "Sign up", createAccount: "Create an account", recaptchaRequired: "Please complete the reCAPTCHA challenge.", termsRequired: "You must accept the Terms of Service and Privacy Policy", accountCreationFailed: "Something went wrong creating your account. Please try again.", accountCreatedGoogle: "Account created with Google.", oneMoreThing: "One more thing", verifyGoogle: "Verify your Google sign-in", completeSecurityCheck: "Complete the security check before continuing with Google.", continueGoogle: "Continue with Google", differentSignIn: "Use a different sign-in method", chooseRole: "Which best describes you?", chooseRoleSubtitle: "Pick a role to finish creating your account.", welcomeBack: "Welcome back", logIn: "Log in", noAccount: "No account?", signUp: "Sign up", orEmail: "or with email", email: "Email", password: "Password", forgotPassword: "Forgot your password?", checkInbox: "Check your inbox", resetLinkSent: "Reset link sent", resetLinkDescription: "If an account exists for {{email}}, we've sent a link to reset the password. It expires in 1 hour.", backToLogin: "Back to login", passwordReset: "Password reset", resetDescription: "Enter your email and we'll send you a link to reset it.", sendResetLink: "Send reset link", missingResetToken: "This link is missing a token", missingResetDescription: "Make sure you opened the full link from your email, or request a new one.", requestNewLink: "Request a new link", success: "Success", redirectingLogin: "Redirecting you to log in…", chooseNewPassword: "Choose a new password", newPassword: "New password", passwordHint: "At least 8 characters, with upper, lower, and a number", confirmNewPassword: "Confirm new password", resetPassword: "Reset password", missingVerificationToken: "This link is missing a verification token.", oneMoment: "One moment", verifyingEmail: "Verifying your email…", verified: "Verified", emailConfirmed: "Email confirmed", emailVerifiedDescription: "Your email is verified. You're all set.", verificationFailed: "Verification failed", linkDidNotWork: "This link didn't work" } },
  am: { common: { mainNavigation: "ዋና ምናሌ", openMenu: "ምናሌ ክፈት", mobileNavigation: "የሞባይል ምናሌ", menu: "ምናሌ", theme: "ገጽታ", searchPages: "ፕሮጀክቶችን፣ ውሎችን እና ገጾችን ፈልግ…", noResults: "ውጤት አልተገኘም።", account: "መለያ" }, auth: { login: "ግባ", signup: "ተመዝገብ", createAccount: "መለያ ፍጠር", recaptchaRequired: "እባክዎ reCAPTCHAን ያጠናቅቁ።", termsRequired: "የአገልግሎት ውሎችንና የግላዊነት መመሪያን መቀበል አለብዎት", accountCreationFailed: "መለያዎን ሲፈጥሩ ችግር ተፈጥሯል። እንደገና ይሞክሩ።", accountCreatedGoogle: "በGoogle መለያ ተፈጥሯል።", oneMoreThing: "አንድ ተጨማሪ ነገር", verifyGoogle: "የGoogle መግቢያዎን ያረጋግጡ", completeSecurityCheck: "በGoogle ከመቀጠልዎ በፊት የደህንነት ምርመራውን ያጠናቅቁ።", continueGoogle: "በGoogle ቀጥል", differentSignIn: "ሌላ የመግቢያ ዘዴ ይጠቀሙ", chooseRole: "የትኛው በተሻለ ይገልጽዎታል?", chooseRoleSubtitle: "መለያዎን ለመፍጠር ሚና ይምረጡ።", welcomeBack: "እንኳን ደህና መጡ", logIn: "ግባ", noAccount: "መለያ የለዎትም?", signUp: "ይመዝገቡ", orEmail: "ወይም በኢሜይል", email: "ኢሜይል", password: "የይለፍ ቃል", forgotPassword: "የይለፍ ቃልዎን ረሱ?", checkInbox: "የገቢ መልዕክትዎን ይመልከቱ", resetLinkSent: "የመቀየሪያ አገናኝ ተልኳል", resetLinkDescription: "ለ{{email}} መለያ ካለ፣ የይለፍ ቃል መቀየሪያ አገናኝ ልከናል። በ1 ሰዓት ውስጥ ያበቃል።", backToLogin: "ወደ መግቢያ ተመለስ", passwordReset: "የይለፍ ቃል ማስተካከያ", resetDescription: "ኢሜይልዎን ያስገቡ፤ ለመቀየር አገናኝ እንልክልዎታለን።", sendResetLink: "የመቀየሪያ አገናኝ ላክ", missingResetToken: "ይህ አገናኝ ምልክት የለውም", missingResetDescription: "ከኢሜይልዎ የተላከውን ሙሉ አገናኝ መክፈትዎን ያረጋግጡ ወይም አዲስ ይጠይቁ።", requestNewLink: "አዲስ አገናኝ ጠይቅ", success: "ተሳክቷል", redirectingLogin: "ወደ መግቢያ በመመለስ ላይ…", chooseNewPassword: "አዲስ የይለፍ ቃል ይምረጡ", newPassword: "አዲስ የይለፍ ቃል", passwordHint: "ቢያንስ 8 ፊደላት፣ ከፍተኛና ዝቅተኛ ፊደል እና ቁጥር ያካትት", confirmNewPassword: "አዲሱን የይለፍ ቃል ያረጋግጡ", resetPassword: "የይለፍ ቃል ቀይር", missingVerificationToken: "ይህ አገናኝ የማረጋገጫ ምልክት የለውም።", oneMoment: "አንድ አፍታ", verifyingEmail: "ኢሜይልዎን በማረጋገጥ ላይ…", verified: "ተረጋግጧል", emailConfirmed: "ኢሜይል ተረጋግጧል", emailVerifiedDescription: "ኢሜይልዎ ተረጋግጧል። ሁሉም ዝግጁ ነው።", verificationFailed: "ማረጋገጫ አልተሳካም", linkDidNotWork: "ይህ አገናኝ አልሰራም" } },
  af: { common: { mainNavigation: "Mariiwwan ijoo", openMenu: "Marii bani", mobileNavigation: "Marii moobaayilaa", menu: "Marii", theme: "Bifa", searchPages: "Pirojektoota, waliigalteewwan fi fuulawwan barbaadi…", noResults: "Bu’aan hin argamne.", account: "Herrega" }, auth: { login: "Seeni", signup: "Galmaa’i", createAccount: "Herrega uumi", recaptchaRequired: "Maaloo qormaata reCAPTCHA xumuri.", termsRequired: "Himata Tajaajilaa fi Imaammata Dhuunfaa fudhachuu qabda", accountCreationFailed: "Herrega kee uumuun rakkoo uumame. Maaloo irra deebi'ii yaali.", accountCreatedGoogle: "Herregni Google'n uumame.", oneMoreThing: "Wanti tokko dabalataa", verifyGoogle: "Seensa Google kee mirkaneessi", completeSecurityCheck: "Google'n itti fufuu kee dura qorannoo nageenyaa xumuri.", continueGoogle: "Google'n itti fufi", differentSignIn: "Mala seensaa biraa fayyadami", chooseRole: "Kan si ibsu isa kami?", chooseRoleSubtitle: "Herrega kee xumuruuf gahee filadhu.", welcomeBack: "Baga deebite", logIn: "Seeni", noAccount: "Herrega hin qabduu?", signUp: "Galmaa’i", orEmail: "ykn imeeliidhaan", email: "Imeelii", password: "Jecha icciitii", forgotPassword: "Jechoota icciitii dagattee?", checkInbox: "Sanduuqa ergaa kee ilaali", resetLinkSent: "Geessituun haaromsaa ergameera", resetLinkDescription: "Herregni {{email}} jira taanaan, geessituu jecha icciitii haaromsuuf ergineerra. Sa'aatii 1 keessatti ni dhumata.", backToLogin: "Gara seensaatti deebi'i", passwordReset: "Jecha icciitii haaromsuu", resetDescription: "Imeelii kee galchi; geessituu ittiin haaromsitu siif ergina.", sendResetLink: "Geessituu haaromsaa ergi", missingResetToken: "Geessituun kun mallattoo hin qabu", missingResetDescription: "Geessituu guutuu imeelii kee keessaa banuu kee mirkaneessi, ykn haaraa gaafadhu.", requestNewLink: "Geessituu haaraa gaafadhu", success: "Milkaa'e", redirectingLogin: "Gara seensaatti deebisaa jira…", chooseNewPassword: "Jecha icciitii haaraa filadhu", newPassword: "Jecha icciitii haaraa", passwordHint: "Yoo xiqqaate arfiilee 8, qubee guddaa, qubee xiqqaa fi lakkoofsa qabaachuu qaba", confirmNewPassword: "Jecha icciitii haaraa mirkaneessi", resetPassword: "Jecha icciitii haaromsi", missingVerificationToken: "Geessituun kun mallattoo mirkaneessaa hin qabu.", oneMoment: "Yeroo xiqqoo", verifyingEmail: "Imeelii kee mirkaneessaa jira…", verified: "Mirkanaa'e", emailConfirmed: "Imeeliin mirkanaa'e", emailVerifiedDescription: "Imeeliin kee mirkanaa'eera. Wanti hundi qophaa'eera.", verificationFailed: "Mirkaneessuun hin milkoofne", linkDidNotWork: "Geessituun kun hin hojjenne" } }
};
const mfaResources = {
  en: { mfa: { security: "Security", sessionExpired: "MFA session expired", signInAgain: "Please sign in again.", returnToLogin: "Return to login", twoFactor: "Two-factor authentication", enterCode: "Enter your MFA code", openAuthenticator: "Open your authenticator app and enter the current 6-digit code.", codeLabel: "Authenticator or recovery code", recoveryHint: "You can also enter one of your recovery codes.", verifySignIn: "Verify and sign in", setupExpired: "MFA setup expired", setupExpiredSettings: "For your security, this setup session is no longer valid. Head back to Settings and start again.", setupExpiredLogin: "For your security, this setup session is no longer valid. Return to login and start again.", setupIncomplete: "Your authenticator setup was not completed. No changes were made to your account.", returnSettings: "Return to settings", enabled: "MFA enabled", protected: "Your account is protected", saveCodes: "Save these recovery codes before continuing. Each code works once if you lose access to your authenticator.", keepPrivate: "Keep these codes private", codesShownOnce: "NexusWork will not show them again after you leave this page.", copied: "Copied", copyCodes: "Copy codes", codesCopied: "Recovery codes copied.", backSettings: "Back to settings", continue: "Continue to NexusWork", protect: "Protect your account", setupTitle: "Set up two-factor authentication", setupSubtitle: "Use an authenticator app to add an extra layer of protection to your NexusWork account.", passwordNotEnough: "Your password alone will no longer be enough to sign in.", openApp: "Open your authenticator app", appDescription: "Use Google Authenticator, Microsoft Authenticator, Authy, or another TOTP app.", addNexus: "Add NexusWork", addDescription: "If your app supports an OTP URI, use the value below. Otherwise, enter the manual setup key.", manualKey: "Manual setup key", copy: "Copy", keyCopied: "Setup key copied.", advancedUri: "Advanced: show OTP URI", uriCopied: "OTP URI copied.", copyUri: "Copy OTP URI", verifyAuthenticator: "Verify your authenticator", verifyDescription: "Enter the current 6-digit code from your app. The code refreshes automatically every few seconds.", sixDigitCode: "6-digit authenticator code", enable: "Enable MFA", afterActivation: "After activation, NexusWork will ask for an authenticator code whenever you sign in.", enterSixDigit: "Enter the 6-digit code shown in your authenticator app." } },
  am: { mfa: { security: "ደህንነት", sessionExpired: "የMFA ክፍለ ጊዜ አልቋል", signInAgain: "እባክዎ እንደገና ይግቡ።", returnToLogin: "ወደ መግቢያ ተመለስ", twoFactor: "ባለሁለት ደረጃ ማረጋገጫ", enterCode: "የMFA ኮድዎን ያስገቡ", openAuthenticator: "የማረጋገጫ መተግበሪያዎን ይክፈቱና የአሁኑን 6 አሃዝ ኮድ ያስገቡ።", codeLabel: "የማረጋገጫ ወይም የመልሶ ማግኛ ኮድ", recoveryHint: "ከመልሶ ማግኛ ኮዶችዎ አንዱንም ማስገባት ይችላሉ።", verifySignIn: "አረጋግጠው ይግቡ", setupExpired: "የMFA ማዘጋጃ ጊዜ አልቋል", setupExpiredSettings: "ለደህንነትዎ ይህ የማዘጋጃ ክፍለ ጊዜ ከእንግዲህ አይሰራም። ወደ ቅንብሮች ተመልሰው እንደገና ይጀምሩ።", setupExpiredLogin: "ለደህንነትዎ ይህ የማዘጋጃ ክፍለ ጊዜ ከእንግዲህ አይሰራም። ወደ መግቢያ ተመልሰው ይጀምሩ።", setupIncomplete: "የማረጋገጫ ማዘጋጀት አልተጠናቀቀም። በመለያዎ ላይ ምንም ለውጥ አልተደረገም።", returnSettings: "ወደ ቅንብሮች ተመለስ", enabled: "MFA ነቅቷል", protected: "መለያዎ ተጠብቋል", saveCodes: "ከመቀጠልዎ በፊት እነዚህን የመልሶ ማግኛ ኮዶች ያስቀምጡ። እያንዳንዱ ኮድ አንድ ጊዜ ብቻ ይሰራል።", keepPrivate: "እነዚህን ኮዶች የግል ያድርጉ", codesShownOnce: "ከዚህ ገጽ ከወጡ በኋላ NexusWork እንደገና አያሳያቸውም።", copied: "ተቀድቷል", copyCodes: "ኮዶችን ቅዳ", codesCopied: "የመልሶ ማግኛ ኮዶች ተቀድተዋል።", backSettings: "ወደ ቅንብሮች ተመለስ", continue: "ወደ NexusWork ቀጥል", protect: "መለያዎን ይጠብቁ", setupTitle: "ባለሁለት ደረጃ ማረጋገጫ ያዘጋጁ", setupSubtitle: "በNexusWork መለያዎ ላይ ተጨማሪ የደህንነት ሽፋን ለመጨመር የማረጋገጫ መተግበሪያ ይጠቀሙ።", passwordNotEnough: "ለመግባት የይለፍ ቃልዎ ብቻ በቂ አይሆንም።", openApp: "የማረጋገጫ መተግበሪያዎን ይክፈቱ", appDescription: "Google Authenticator፣ Microsoft Authenticator፣ Authy ወይም ሌላ TOTP መተግበሪያ ይጠቀሙ።", addNexus: "NexusWorkን ያክሉ", addDescription: "መተግበሪያዎ OTP URIን የሚደግፍ ከሆነ ከታች ያለውን ይጠቀሙ። ካልሆነ የማዘጋጃ ቁልፉን በእጅ ያስገቡ።", manualKey: "የማዘጋጃ ቁልፍ", copy: "ቅዳ", keyCopied: "የማዘጋጃ ቁልፍ ተቀድቷል።", advancedUri: "የላቀ፦ OTP URI አሳይ", uriCopied: "OTP URI ተቀድቷል።", copyUri: "OTP URI ቅዳ", verifyAuthenticator: "ማረጋገጫዎን ያረጋግጡ", verifyDescription: "ከመተግበሪያዎ የአሁኑን 6 አሃዝ ኮድ ያስገቡ። ኮዱ በየጥቂት ሰከንዶች በራስ-ሰር ይቀየራል።", sixDigitCode: "6 አሃዝ የማረጋገጫ ኮድ", enable: "MFA አንቃ", afterActivation: "ከነቃ በኋላ NexusWork በሚገቡበት ጊዜ ሁሉ የማረጋገጫ ኮድ ይጠይቃል።", enterSixDigit: "በማረጋገጫ መተግበሪያዎ ላይ የሚታየውን 6 አሃዝ ኮድ ያስገቡ።" } },
  af: { mfa: { security: "Nageenya", sessionExpired: "Yeroon MFA dhumera", signInAgain: "Maaloo irra deebi'ii seeni.", returnToLogin: "Gara seensaatti deebi'i", twoFactor: "Mirkaneessa sadarkaa lamaa", enterCode: "Koodii MFA kee galchi", openAuthenticator: "Appii mirkaneessaa kee baniitii koodii lakkoofsa 6 yeroo ammaa galchi.", codeLabel: "Koodii mirkaneessaa ykn deebisanii argachuu", recoveryHint: "Koodiiwwan deebisanii argachuu keessaa tokko galchuu dandeessa.", verifySignIn: "Mirkaneessiitii seeni", setupExpired: "Yeroon qophii MFA dhumera", setupExpiredSettings: "Nageenya keetiif, yeroo qophii kun sirrii miti. Gara Qindaa'inaatti deebi'ii irra deebi'ii jalqabi.", setupExpiredLogin: "Nageenya keetiif, yeroo qophii kun sirrii miti. Gara seensaatti deebi'ii irra deebi'ii jalqabi.", setupIncomplete: "Qophiin mirkaneessaa hin xumuramne. Herrega kee irratti jijjiiramni hin godhamne.", returnSettings: "Gara qindaa'inatti deebi'i", enabled: "MFA banameera", protected: "Herregni kee eegameera", saveCodes: "Itti fufuu kee dura koodiiwwan deebisanii argachuu kana olkaa'i. Tokkoon tokkoon koodii yeroo tokko qofa hojjeta.", keepPrivate: "Koodiiwwan kana iccitii godhi", codesShownOnce: "Fuula kana erga baatee booda NexusWork irra deebi'ee isaan hin agarsiisu.", copied: "Qophaa'eera", copyCodes: "Koodiiwwan kopi godhi", codesCopied: "Koodiiwwan deebisanii argachuu kopi godhameera.", backSettings: "Gara qindaa'inatti deebi'i", continue: "Gara NexusWork itti fufi", protect: "Herrega kee eegi", setupTitle: "Mirkaneessa sadarkaa lamaa qopheessi", setupSubtitle: "Herrega NexusWork kee irratti eegumsa dabalataa uumuuf appii mirkaneessaa fayyadami.", passwordNotEnough: "Jecha icciitii kee qofaan seenuun gahaa hin ta'u.", openApp: "Appii mirkaneessaa kee bani", appDescription: "Google Authenticator, Microsoft Authenticator, Authy ykn appii TOTP biraa fayyadami.", addNexus: "NexusWork dabali", addDescription: "Appiin kee OTP URI yoo deeggaru gatii armaan gadii fayyadami. Yoo hin taane, furtuu qophii harkaan galchi.", manualKey: "Furtuu qophii harkaa", copy: "Kopi godhi", keyCopied: "Furtuun qophii kopi godhameera.", advancedUri: "Sadarkaa olaanaa: OTP URI agarsiisi", uriCopied: "OTP URI kopi godhameera.", copyUri: "OTP URI kopi godhi", verifyAuthenticator: "Mirkaneessaa kee mirkaneessi", verifyDescription: "Koodii lakkoofsa 6 yeroo ammaa appii kee irraa galchi. Koodichi sekondii muraasa muraasaan ofumaan haaroma.", sixDigitCode: "Koodii mirkaneessaa lakkoofsa 6", enable: "MFA bani", afterActivation: "Erga banamee booda NexusWork yeroo seentu hunda koodii mirkaneessaa si gaafata.", enterSixDigit: "Koodii lakkoofsa 6 appii mirkaneessaa kee irratti mul'atu galchi." } }
};
const registrationResources = {
  en: { registration: { passwordLength: "At least 8 characters", passwordLower: "Include at least one lowercase letter", passwordUpper: "Include at least one uppercase letter", passwordNumber: "Include at least one number", nameRequired: "Enter your name", emailInvalid: "Enter a valid email", passwordMismatch: "Passwords don't match", phoneInvalid: "Enter a valid phone number", accountCreated: "Account created. Check your email to verify it.", getStarted: "Get started", subtitle: "Join as a student looking for work, a client with work to post, or university staff.", haveAccount: "Already have an account?", googleHint: "Sign up with Google and you're in — no extra fields needed right now.", fullName: "Full name", confirmPassword: "Confirm password", next: "Next", phone: "Phone number", phonePlaceholder: "e.g. +251 9XX XXX XXX", phoneHint: "You can add this later from your profile if you'd rather skip it now.", hide: "Hide", add: "Add", student: "student", client: "client", detailsOptional: "details (optional)", studentInformation: "Student information", studentInfoHint: "Optional for now — used later for university verification. You can fill this in any time from your profile settings.", university: "University", loadingUniversities: "Loading universities…", selectUniversity: "Select your university", noUniversity: "No university is registered on NexusWork yet. Ask an administrator to add yours.", chooseUniversity: "Choose the university where you are enrolled.", studentId: "Student ID number", studentIdPlaceholder: "e.g. UGR/1234/15", enrollmentStatus: "Enrollment status", program: "Program / field of study", programPlaceholder: "e.g. BSc Computer Science", clientInformation: "Client information", clientInfoHint: "Optional — tell students whether you're hiring personally or on behalf of an organization. You can add this later from your profile settings.", clientType: "Client type", organizationName: "Organization name", organizationPlaceholder: "Your company, NGO, department, or organization", back: "Back", finish: "Finish registration", enrollment: { enrolled: "Currently enrolled", on_leave: "Currently on leave", graduated: "Graduated" }, organization: { individual: "Individual", company: "Company", university_department: "University department", ngo: "NGO", government: "Government organization" } } },
  am: { registration: { passwordLength: "ቢያንስ 8 ፊደላት", passwordLower: "ቢያንስ አንድ ትንሽ ፊደል ያካትት", passwordUpper: "ቢያንስ አንድ ትልቅ ፊደል ያካትት", passwordNumber: "ቢያንስ አንድ ቁጥር ያካትት", nameRequired: "ስምዎን ያስገቡ", emailInvalid: "ትክክለኛ ኢሜይል ያስገቡ", passwordMismatch: "የይለፍ ቃሎች አይዛመዱም", phoneInvalid: "ትክክለኛ ስልክ ቁጥር ያስገቡ", accountCreated: "መለያ ተፈጥሯል። ኢሜይልዎን ያረጋግጡ።", getStarted: "ይጀምሩ", subtitle: "ሥራ እንደሚፈልግ ተማሪ፣ ሥራ እንደሚያቀርብ ደንበኛ ወይም የዩኒቨርሲቲ ሠራተኛ ይቀላቀሉ።", haveAccount: "መለያ አለዎት?", googleHint: "በGoogle ይመዝገቡ — አሁን ተጨማሪ መረጃ አያስፈልግም።", fullName: "ሙሉ ስም", confirmPassword: "የይለፍ ቃል ያረጋግጡ", next: "ቀጣይ", phone: "ስልክ ቁጥር", phonePlaceholder: "ለምሳሌ +251 9XX XXX XXX", phoneHint: "ከፈለጉ በኋላ ከመገለጫዎ ላይ ማከል ይችላሉ።", hide: "ደብቅ", add: "አክል", student: "የተማሪ", client: "የደንበኛ", detailsOptional: "መረጃ (አማራጭ)", studentInformation: "የተማሪ መረጃ", studentInfoHint: "ለአሁን አማራጭ ነው — በኋላ ለዩኒቨርሲቲ ማረጋገጫ ይጠቅማል።", university: "ዩኒቨርሲቲ", loadingUniversities: "ዩኒቨርሲቲዎች በመጫን ላይ…", selectUniversity: "ዩኒቨርሲቲዎን ይምረጡ", noUniversity: "እስካሁን ምንም ዩኒቨርሲቲ አልተመዘገበም። አስተዳዳሪ እንዲያክል ይጠይቁ።", chooseUniversity: "የተመዘገቡበትን ዩኒቨርሲቲ ይምረጡ።", studentId: "የተማሪ መታወቂያ ቁጥር", studentIdPlaceholder: "ለምሳሌ UGR/1234/15", enrollmentStatus: "የምዝገባ ሁኔታ", program: "የትምህርት መርሃ ግብር / ዘርፍ", programPlaceholder: "ለምሳሌ BSc Computer Science", clientInformation: "የደንበኛ መረጃ", clientInfoHint: "አማራጭ — በግል ወይም በድርጅት ስም እንደሚቀጥሩ ለተማሪዎች ይንገሩ።", clientType: "የደንበኛ አይነት", organizationName: "የድርጅት ስም", organizationPlaceholder: "የኩባንያ፣ NGO፣ የመምሪያ ወይም የድርጅት ስም", back: "ተመለስ", finish: "ምዝገባ ጨርስ", enrollment: { enrolled: "አሁን በትምህርት ላይ", on_leave: "በእረፍት ላይ", graduated: "ተመርቋል" }, organization: { individual: "ግለሰብ", company: "ኩባንያ", university_department: "የዩኒቨርሲቲ መምሪያ", ngo: "NGO", government: "የመንግሥት ድርጅት" } } },
  af: { registration: { passwordLength: "Yoo xiqqaate arfiilee 8", passwordLower: "Yoo xiqqaate qubee xiqqaa tokko qabaadhu", passwordUpper: "Yoo xiqqaate qubee guddaa tokko qabaadhu", passwordNumber: "Yoo xiqqaate lakkoofsa tokko qabaadhu", nameRequired: "Maqaa kee galchi", emailInvalid: "Imeelii sirrii galchi", passwordMismatch: "Jechoonni icciitii wal hin siman", phoneInvalid: "Lakkoofsa bilbilaa sirrii galchi", accountCreated: "Herregni uumameera. Imeelii kee mirkaneessi.", getStarted: "Jalqabi", subtitle: "Barataa hojii barbaadu, maamilaa hojii maxxansu ykn hojjetaa yuunivarsiitii ta'uun makami.", haveAccount: "Herrega qabdaa?", googleHint: "Google'n galmaa'i — amma odeeffannoo dabalataa hin barbaachisu.", fullName: "Maqaa guutuu", confirmPassword: "Jecha icciitii mirkaneessi", next: "Itti aanee", phone: "Lakkoofsa bilbilaa", phonePlaceholder: "fkn. +251 9XX XXX XXX", phoneHint: "Yoo barbaadde booda profaayila kee irraa dabali.", hide: "Dhoki", add: "Dabali", student: "barataa", client: "maamilaa", detailsOptional: "odeeffannoo (filannoo)", studentInformation: "Odeeffannoo barataa", studentInfoHint: "Ammaaf filannoo dha — booda mirkaneessa yuunivarsiitii keessatti fayyada.", university: "Yuunivarsiitii", loadingUniversities: "Yuunivarsiitiiwwan fe'amaa jiru…", selectUniversity: "Yuunivarsiitii kee filadhu", noUniversity: "Ammaaf yuunivarsiitiin hin galmoofne. Bulchaa akka dabalu gaafadhu.", chooseUniversity: "Yuunivarsiitii itti barattu filadhu.", studentId: "Lakkoofsa eenyummaa barataa", studentIdPlaceholder: "fkn. UGR/1234/15", enrollmentStatus: "Haala galmee", program: "Sagantaa / damee barnootaa", programPlaceholder: "fkn. BSc Computer Science", clientInformation: "Odeeffannoo maamilaa", clientInfoHint: "Filannoo — dhuunfaan ykn dhaabbata bakka bu'uun akka qacartu barattootatti himi.", clientType: "Gosa maamilaa", organizationName: "Maqaa dhaabbataa", organizationPlaceholder: "Maqaa dhaabbata, NGO, waajjira ykn dhaabbataa kee", back: "Duubatti", finish: "Galmee xumuri", enrollment: { enrolled: "Amma barachaa jira", on_leave: "Boqonnaa irra jira", graduated: "Eebbifameera" }, organization: { individual: "Dhuunfaa", company: "Kampaanii", university_department: "Kutaa yuunivarsiitii", ngo: "NGO", government: "Dhaabbata mootummaa" } } }
};
const dashboardResources = {
  en: { dashboard: { there: "there", workspace: "Workspace", welcome: "Welcome back, {{name}}", staffPendingTitle: "Staff access pending admin approval", staffPendingDescription: "Matching your university's email domain only confirmed eligibility. Submit your staff ID or HR letter from your profile so an admin can approve your account.", submitVerification: "Submit verification", overview: "Overview", analytics: "Dashboard analytics", noData: "No data yet.", liveSources: "Live data sources", metricsDescription: "Metrics update from your authenticated workspace data.", recordsShown: "Records shown", lastLoaded: "Last loaded", live: "Live", roles: { student: "Student", client: "Client", university_staff: "University staff", admin: "Administrator" } } },
  am: { dashboard: { there: "እርስዎ", workspace: "የሥራ ቦታ", welcome: "እንኳን ደህና መጡ፣ {{name}}", staffPendingTitle: "የሠራተኛ መዳረሻ የአስተዳዳሪ ፈቃድ እየጠበቀ ነው", staffPendingDescription: "የዩኒቨርሲቲ ኢሜይል ጎራዎ ብቁነትን ብቻ አረጋግጧል። አስተዳዳሪ መለያዎን እንዲያጸድቅ የሠራተኛ መታወቂያዎን ወይም የHR ደብዳቤዎን ከመገለጫዎ ያስገቡ።", submitVerification: "ማረጋገጫ አስገባ", overview: "አጠቃላይ እይታ", analytics: "የዳሽቦርድ ትንታኔ", noData: "እስካሁን መረጃ የለም።", liveSources: "የቀጥታ መረጃ ምንጮች", metricsDescription: "መለኪያዎች ከተረጋገጠው የሥራ ቦታ መረጃዎ ይዘምናሉ።", recordsShown: "የታዩ መዝገቦች", lastLoaded: "ለመጨረሻ ጊዜ የተጫነው", live: "ቀጥታ", roles: { student: "ተማሪ", client: "ደንበኛ", university_staff: "የዩኒቨርሲቲ ሠራተኛ", admin: "አስተዳዳሪ" } } },
  af: { dashboard: { there: "achi", workspace: "Bakka hojii", welcome: "Baga deebite, {{name}}", staffPendingTitle: "Hayyamni hojjetaa eebba bulchaa eeggataa jira", staffPendingDescription: "Daandiin imeelii yuunivarsiitii kee ulaagaa guutuu qofa mirkaneesse. Bulchaan herrega kee akka eebuuf eenyummaa hojjetaa ykn xalayaa HR profaayila kee irraa galchi.", submitVerification: "Mirkaneessa galchi", overview: "Ilaalcha waliigalaa", analytics: "Xiinxala daashboordii", noData: "Ammaaf daataan hin jiru.", liveSources: "Maddoota daataa kallattii", metricsDescription: "Safartuun daataa bakka hojii kee mirkanaa'e irraa haaroma.", recordsShown: "Galmeewwan mul'atan", lastLoaded: "Yeroo dhumaaf fe'ame", live: "Kallattii", roles: { student: "Barataa", client: "Maamilaa", university_staff: "Hojjetaa yuunivarsiitii", admin: "Bulchaa" } } }
};
const directoryResources = {
  en: { students: { marketplace: "Student marketplace", title: "Find verified student talent", description: "Every profile is backed by a real university. Skills are certified or self-reported — always clearly marked.", searchPlaceholder: "Search by skill, department, or name", noResults: "No students found", noResultsHint: "Try a broader search or clear your filters.", verified: "Verified", universityStudent: "University student", remote: "Remote", viewProfile: "View profile", departments: { all: "All departments", cs: "Computer Science", software: "Software Engineering", it: "Information Technology", is: "Information Systems" } } },
  am: { students: { marketplace: "የተማሪዎች የገበያ መድረክ", title: "የተረጋገጡ የተማሪ ተሰጥኦዎችን ያግኙ", description: "እያንዳንዱ መገለጫ በእውነተኛ ዩኒቨርሲቲ የተደገፈ ነው። ክህሎቶች የተረጋገጡ ወይም በተማሪው የተገለጹ መሆናቸው በግልጽ ይታያል።", searchPlaceholder: "በክህሎት፣ በመምሪያ ወይም በስም ይፈልጉ", noResults: "ተማሪዎች አልተገኙም", noResultsHint: "ሰፋ ያለ ፍለጋ ይሞክሩ ወይም ማጣሪያዎቹን ያጽዱ።", verified: "ተረጋግጧል", universityStudent: "የዩኒቨርሲቲ ተማሪ", remote: "ከርቀት", viewProfile: "መገለጫ ይመልከቱ", departments: { all: "ሁሉም መምሪያዎች", cs: "የኮምፒውተር ሳይንስ", software: "የሶፍትዌር ምህንድስና", it: "የኢንፎርሜሽን ቴክኖሎጂ", is: "የኢንፎርሜሽን ሲስተምስ" } } },
  af: { students: { marketplace: "Gabaa barattootaa", title: "Dandeettii barataa mirkanaa'e argadhu", description: "Profaayiliin hundi yuunivarsiitii dhugaatiin deeggarama. Dandeettiin mirkanaa'e ykn ofiin gabaafame ta'uu isaa ifatti mul'ata.", searchPlaceholder: "Dandeettii, kutaa ykn maqaan barbaadi", noResults: "Barattoonni hin argamne", noResultsHint: "Barbaacha bal'aa yaali ykn calaltuu qulqulleessi.", verified: "Mirkanaa'e", universityStudent: "Barataa yuunivarsiitii", remote: "Fagoo", viewProfile: "Profaayila ilaali", departments: { all: "Kutaawwan hunda", cs: "Saayinsii Kompiitaraa", software: "Injinariingii Softiweeraa", it: "Teeknooloojii Odeeffannoo", is: "Sirna Odeeffannoo" } } }
};
const dashboardRoleResources = {
  en: { dashboard: { student: { heading: "Active proposals and contracts", body: "Track proposals you've sent, milestones in progress, and funds released to your wallet.", primary: "Browse open projects" }, client: { heading: "Your posted projects", body: "Review incoming proposals, fund milestones, and approve delivered work.", primary: "Post a project" }, staff: { heading: "Verification queue", body: "Confirm student enrollment so verified badges can appear on their proposals." }, admin: { heading: "Platform overview", body: "Monitor activity across clients, students, and universities." } } },
  am: { dashboard: { student: { heading: "ንቁ ፕሮፖዛሎችና ውሎች", body: "ያቀረቧቸውን ፕሮፖዛሎች፣ በሂደት ላይ ያሉ ደረጃዎችንና ወደ ቦርሳዎ የተለቀቁ ገንዘቦችን ይከታተሉ።", primary: "ክፍት ፕሮጀክቶችን ይመልከቱ" }, client: { heading: "ያስቀመጧቸው ፕሮጀክቶች", body: "የሚመጡ ፕሮፖዛሎችን ይገምግሙ፣ ደረጃዎችን ይደጉሙና የተሰጠውን ሥራ ያጽድቁ።", primary: "ፕሮጀክት ያቅርቡ" }, staff: { heading: "የማረጋገጫ ወረፋ", body: "የተረጋገጡ ምልክቶች በፕሮፖዛሎቻቸው ላይ እንዲታዩ የተማሪዎችን ምዝገባ ያረጋግጡ።" }, admin: { heading: "የመድረክ አጠቃላይ እይታ", body: "በደንበኞች፣ በተማሪዎችና በዩኒቨርሲቲዎች ያለውን እንቅስቃሴ ይከታተሉ።" } } },
  af: { dashboard: { student: { heading: "Pirooppoozaalaa fi waliigalteewwan hojii irra jiran", body: "Pirooppoozaala ergite, milestoona adeemaa jiru fi maallaqa boorsaa kee keessatti gadhiifame hordofi.", primary: "Pirojektoota banaa ilaali" }, client: { heading: "Pirojektoota maxxansite", body: "Pirooppoozaala dhufan ilaali, milestoona maallaqaan deeggaruu fi hojii kenname eebi.", primary: "Pirojektii maxxansi" }, staff: { heading: "Tarree mirkaneessaa", body: "Mallattoon mirkanaa'e pirooppoozaala isaanii irratti akka mul'atuuf galmee barattootaa mirkaneessi." }, admin: { heading: "Ilaalcha waliigalaa waltajjii", body: "Sochii maamiltootaa, barattootaa fi yuunivarsiitiiwwanii hordofi." } } }
};
const dashboardDetailsResources = {
  am: { dashboard: { details: { student: { stat0: { label: "ክፍት ፕሮፖዛሎች", hint: "የደንበኛ ግምገማ እየጠበቁ" }, stat1: { label: "ንቁ ውሎች", hint: "ደረጃዎች በሂደት ላይ" }, stat2: { label: "በኤስክሮ ያለ", hint: "የተደገፈ ነገር ግን ገና ያልተለቀቀ" }, action0: { label: "ሥራ ያግኙ", body: "ከክህሎትዎ ጋር የሚጣጣሙ ሥራዎችን ይፈልጉ።" }, action1: { label: "ውሎቼ", body: "ደረጃዎችን ያስረክቡና ፈቃድ ይጠይቁ።" }, action2: { label: "ቦርሳ", body: "የተለቀቁ ክፍያዎችንና ቀሪ ሂሳቦችን ይከታተሉ።" } }, client: { stat0: { label: "ንቁ ፕሮጀክቶች", hint: "በአሁኑ ጊዜ ፕሮፖዛል የሚቀበሉ" }, stat1: { label: "አዲስ ፕሮፖዛሎች", hint: "የእርስዎን ግምገማ እየጠበቁ" }, stat2: { label: "በኤስክሮ ያለ ገንዘብ", hint: "እስኪያጸድቁ ድረስ የተያዘ" }, action0: { label: "ሥራ ያቅርቡ", body: "ሥራውን ይግለጹና ደረጃዎችን ያዘጋጁ።" }, action1: { label: "ውሎች", body: "የተሰጡ ሥራዎችን ያጽድቁና ገንዘብ ይልቀቁ።" }, action2: { label: "ቦርሳ", body: "ኤስክሮን ይደጉሙና የክፍያ ታሪክን ይመልከቱ።" } }, university_staff: { stat0: { label: "በመጠባበቅ ላይ ያሉ ጥያቄዎች", hint: "ማረጋገጫ የሚጠብቁ ተማሪዎች" }, stat1: { label: "የጸደቁ", hint: "ምዝገባዎች ተረጋግጠዋል" }, stat2: { label: "ውድቅ የተደረጉ", hint: "በዩኒቨርሲቲው ያልተረጋገጡ" } }, admin: { stat0: { label: "ንቁ ተጠቃሚዎች", hint: "ባለፉት 30 ቀናት የገቡ" }, stat1: { label: "ክፍት ክርክሮች", hint: "መፍትሄ የሚፈልጉ" }, stat2: { label: "የመድረክ ኮሚሽን", hint: "የተመዘገበ የተሳካ ኮሚሽን" } } } } },
  af: { dashboard: { details: { student: { stat0: { label: "Pirooppoozaalaa banaa", hint: "Mirkaneessa maamilaa eeggataa" }, stat1: { label: "Waliigalteewwan hojii irra jiran", hint: "Milestoona adeemaa jiru" }, stat2: { label: "Eskroo keessa", hint: "Deeggarameera, ammaaf hin gadhiifamne" }, action0: { label: "Hojii barbaadi", body: "Hojii dandeettii kee waliin walsimu barbaadi." }, action1: { label: "Waliigalteewwan koo", body: "Milestoona galchiitii eebba gaafadhu." }, action2: { label: "Boorsaa", body: "Kaffaltii fi hafe hordofi." } }, client: { stat0: { label: "Pirojektoota kallattii", hint: "Amma pirooppoozaala fudhataa jiran" }, stat1: { label: "Pirooppoozaala haaraa", hint: "Gama kee irraa ilaalamuu eeggataa" }, stat2: { label: "Maallaqa eskroo keessa", hint: "Hanga ati eebbitutti qabame" }, action0: { label: "Hojii maxxansi", body: "Hojii ibsiitii milestoona qopheessi." }, action1: { label: "Waliigalteewwan", body: "Hojii kenname eebbiitii maallaqa gadhiisi." }, action2: { label: "Boorsaa", body: "Eskroo guutii seenaa kaffaltii ilaali." } }, university_staff: { stat0: { label: "Gaaffiiwwan eeggataa jiran", hint: "Barattoota mirkaneessa eeggatan" }, stat1: { label: "Eebbifaman", hint: "Galmeen mirkanaa'e" }, stat2: { label: "Didaman", hint: "Yuunivarsiitiin hin mirkanoofne" } }, admin: { stat0: { label: "Fayyadamtoota kallattii", hint: "Guyyaa 30 darban keessatti seenan" }, stat1: { label: "Falmiilee banaa", hint: "Furmaata barbaadan" }, stat2: { label: "Komishinii waltajjii", hint: "Komishinii milkaa'e galmaa'e" } } } } }
};
const profileResources = {
  en: { profile: { backToProfile: "Back to profile", settings: "Profile settings", editTitle: "Edit your profile", editDescription: "Keep your professional information up to date so clients and universities can understand your skills and experience.", photo: "Profile photo", changePhoto: "Change photo", photoHint: "JPG, PNG or WEBP. Maximum 5MB.", basicInformation: "Basic information", fullNamePlaceholder: "Your full name", emailCannotChange: "Your university email cannot be changed here.", headline: "Professional headline", headlinePlaceholder: "e.g. Computer Science Student & Full-Stack Developer", about: "About you", aboutPlaceholder: "Tell clients about yourself, your experience, and what you can help them with...", education: "Education", department: "Department", skills: "Skills", skillsHint: "Add the skills you want clients to discover you for.", skillsPlaceholder: "React, Node.js, MongoDB, UI/UX...", saveChanges: "Save changes" } },
  am: { profile: { backToProfile: "ወደ መገለጫ ተመለስ", settings: "የመገለጫ ቅንብሮች", editTitle: "መገለጫዎን ያስተካክሉ", editDescription: "ደንበኞችና ዩኒቨርሲቲዎች ክህሎትዎንና ልምድዎን እንዲያውቁ የሙያ መረጃዎን ወቅታዊ ያድርጉ።", photo: "የመገለጫ ፎቶ", changePhoto: "ፎቶ ቀይር", photoHint: "JPG፣ PNG ወይም WEBP። ከፍተኛው 5MB።", basicInformation: "መሠረታዊ መረጃ", fullNamePlaceholder: "ሙሉ ስምዎ", emailCannotChange: "የዩኒቨርሲቲ ኢሜይልዎ እዚህ ሊቀየር አይችልም።", headline: "የሙያ ርዕስ", headlinePlaceholder: "ለምሳሌ የኮምፒውተር ሳይንስ ተማሪ እና ፉል-ስታክ ዴቨሎፐር", about: "ስለ እርስዎ", aboutPlaceholder: "ስለራስዎ፣ ልምድዎና ሊረዱበት ስለሚችሉት ለደንበኞች ይንገሩ...", education: "ትምህርት", department: "መምሪያ", skills: "ክህሎቶች", skillsHint: "ደንበኞች እንዲያገኙዎት የሚፈልጓቸውን ክህሎቶች ያክሉ።", skillsPlaceholder: "React፣ Node.js፣ MongoDB፣ UI/UX...", saveChanges: "ለውጦችን አስቀምጥ" } },
  af: { profile: { backToProfile: "Gara profaayilaatti deebi'i", settings: "Qindaa'ina profaayilaa", editTitle: "Profaayila kee gulaali", editDescription: "Odeeffannoo ogummaa kee haaromsi; maamiltoonni fi yuunivarsiitiiwwan dandeettii fi muuxannoo kee akka hubatan gargaara.", photo: "Suuraa profaayilaa", changePhoto: "Suuraa jijjiiri", photoHint: "JPG, PNG ykn WEBP. Hanga 5MB.", basicInformation: "Odeeffannoo bu'uuraa", fullNamePlaceholder: "Maqaa kee guutuu", emailCannotChange: "Imeeliin yuunivarsiitii kee asitti jijjiiramuu hin danda'u.", headline: "Mataduree ogummaa", headlinePlaceholder: "fkn. Barataa Saayinsii Kompiitaraa fi Full-Stack Developer", about: "Waa'ee kee", aboutPlaceholder: "Waa'ee kee, muuxannoo kee fi waan isaan gargaaruu dandeessu maamiltootatti himi...", education: "Barnoota", department: "Kutaa", skills: "Dandeettiiwwan", skillsHint: "Dandeettiiwwan maamiltoonni si argachuuf barbaadan dabali.", skillsPlaceholder: "React, Node.js, MongoDB, UI/UX...", saveChanges: "Jijjiirama olkaa'i" } }
};
const profileOverviewResources = {
  en: { profile: { updated: "Profile updated.", saveError: "We couldn't save your profile. Please try again.", photoUpdated: "Profile photo updated.", photoRemoved: "Profile photo removed.", generalIdentity: "General & Identity", verification: "Verification ✓", verificationRequest: "Verification Request", strengthSecurity: "Strength & Security", title: "Profile & settings", description: "Keep your profile up to date for client proposals and university verification.", discard: "Discard changes", sections: "Profile sections" } },
  am: { profile: { updated: "መገለጫ ተዘምኗል።", saveError: "መገለጫዎን ማስቀመጥ አልተቻለም። እንደገና ይሞክሩ።", photoUpdated: "የመገለጫ ፎቶ ተዘምኗል።", photoRemoved: "የመገለጫ ፎቶ ተወግዷል።", generalIdentity: "አጠቃላይ እና ማንነት", verification: "ማረጋገጫ ✓", verificationRequest: "የማረጋገጫ ጥያቄ", strengthSecurity: "ጥንካሬ እና ደህንነት", title: "መገለጫ እና ቅንብሮች", description: "ለደንበኛ ፕሮፖዛሎችና ለዩኒቨርሲቲ ማረጋገጫ መገለጫዎን ወቅታዊ ያድርጉ።", discard: "ለውጦችን ተው", sections: "የመገለጫ ክፍሎች" } },
  af: { profile: { updated: "Profaayilaan haaromfameera.", saveError: "Profaayila kee olkaa'uu hin dandeenye. Maaloo irra deebi'ii yaali.", photoUpdated: "Suuraan profaayilaa haaromfameera.", photoRemoved: "Suuraan profaayilaa haqameera.", generalIdentity: "Waliigalaa fi Eenyummaa", verification: "Mirkaneessa ✓", verificationRequest: "Gaaffii mirkaneessaa", strengthSecurity: "Jabinaa fi Nageenya", title: "Profaayila fi qindaa'ina", description: "Profaayila kee pirooppoozaala maamilaa fi mirkaneessa yuunivarsiitii tiif haaromsi.", discard: "Jijjiirama dhiisi", sections: "Kutaa profaayilaa" } }
};
const profileFieldResources = {
  am: { profile: { checkDetails: "ዝርዝርዎን ይመልከቱ", generalProfile: "አጠቃላይ መገለጫ", generalProfileDescription: "በይፋዊ መገለጫዎ ላይ የሚታዩ የማንነት፣ የሕይወት ታሪክና የፖርትፎሊዮ መረጃዎች።", emailAddress: "የኢሜይል አድራሻ", shortBio: "አጭር የሕይወት ታሪክ", bioPlaceholder: "ስለ ሙያዎና ግቦችዎ አጭር መግለጫ...", location: "አካባቢ", locationPlaceholder: "አዲስ አበባ", enrollmentHint: "ለደንበኞች ይታያል፤ ዩኒቨርሲቲዎም ለማረጋገጫ ይጠቀምበታል።", skillsExample: "React፣ Python፣ Figma", portfolioUrl: "የፖርትፎሊዮ URL", strengthTitle: "የመገለጫ ጥንካሬ", strengthDescription: "የተሟሉ መገለጫዎች ተጨማሪ ግብዣዎችን ያገኛሉ።", stillToAdd: "እስካሁን የሚጨመር", everythingComplete: "ሁሉም ተሞልቷል — ጥሩ ሥራ። ወቅታዊ እንዲሆን በየሴሚስተሩ ይመልከቱ።", sectionsComplete: "{{done}} ከ{{total}} ክፍሎች ተጠናቀዋል", percentComplete: "{{percent}}% ተጠናቋል" } },
  af: { profile: { checkDetails: "Odeeffannoo kee ilaali", generalProfile: "Profaayila waliigalaa", generalProfileDescription: "Odeeffannoo eenyummaa, seenaa gabaabaa fi poortifooliyoo profaayila uummataa kee irratti mul'atu.", emailAddress: "Teessoo imeelii", shortBio: "Seenaa gabaabaa", bioPlaceholder: "Waa'ee ogummaa fi galma kee ibsa gabaabaa...", location: "Bakka", locationPlaceholder: "Finfinnee", enrollmentHint: "Maamiltootatti mul'ata; yuunivarsiitiin kees mirkaneessuuf itti fayyadama.", skillsExample: "React, Python, Figma", portfolioUrl: "URL poortifooliyoo", strengthTitle: "Jabina profaayilaa", strengthDescription: "Profaayiloonni guutuun affeerraa dabalataa argatu.", stillToAdd: "Ammas dabalamuu qabu", everythingComplete: "Wanti hundi guutameera — hojii gaarii. Yeroo yeroon haaromsi.", sectionsComplete: "Kutaa {{done}} keessaa {{total}} xumurame", percentComplete: "%{{percent}} xumurame" } }
};
const skillsResources = {
  en: { skills: { grow: "Grow", title: "Skill taxonomy", description: "Structured skills (category + name + level) drive search, matching, and certification.", noSkills: "No skills registered yet", noSkillsHint: "The taxonomy will populate as students register and projects are tagged." } },
  am: { skills: { grow: "ያድጉ", title: "የክህሎት ምድብ", description: "የተደራጁ ክህሎቶች (ምድብ + ስም + ደረጃ) ፍለጋን፣ ተዛማጅነትንና ማረጋገጫን ይመራሉ።", noSkills: "እስካሁን ክህሎት አልተመዘገበም", noSkillsHint: "ተማሪዎች ሲመዘገቡና ፕሮጀክቶች ሲመደቡ ዝርዝሩ ይሞላል።" } },
  af: { skills: { grow: "Guddadhu", title: "Ramaddii dandeettii", description: "Dandeettiin qindaa'aan (ramaddii + maqaa + sadarkaa) barbaacha, walitti firooma fi mirkaneessa hooggana.", noSkills: "Ammaaf dandeettiin hin galmoofne", noSkillsHint: "Barattoonni yeroo galmaa'anii fi pirojektoonni yeroo mallatteeffaman tarreen ni guutama." } }
};
const universityResources = {
  en: { universities: { hub: "University hub", title: "Verify, certify, and grow your student talent", verifications: "Verifications", submitStaffVerification: "Submit staff verification", noUniversities: "No universities registered yet.", pending: "Pending", rejected: "Rejected" } },
  am: { universities: { hub: "የዩኒቨርሲቲ ማዕከል", title: "የተማሪ ተሰጥኦዎን ያረጋግጡ፣ ያረጋግጡ እና ያሳድጉ", verifications: "ማረጋገጫዎች", submitStaffVerification: "የሠራተኛ ማረጋገጫ አስገባ", noUniversities: "እስካሁን ዩኒቨርሲቲ አልተመዘገበም።", pending: "በመጠባበቅ ላይ", rejected: "ውድቅ የተደረገ" } },
  af: { universities: { hub: "Giddugala yuunivarsiitii", title: "Dandeettii barattootaa kee mirkaneessi, ragaa kenni fi guddisi", verifications: "Mirkaneessawwan", submitStaffVerification: "Mirkaneessa hojjetaa galchi", noUniversities: "Ammaaf yuunivarsiitiin hin galmoofne.", pending: "Eeggataa", rejected: "Didame" } }
};
const projectResources = {
  en: { projects: { marketplace: "Marketplace Briefs", title: "Explore Open Projects", search: "Search projects", searchPlaceholder: "Search by title, skill or keyword...", category: "Category", allCategories: "All categories", experience: "Experience level", sortBy: "Sort by", clearFilters: "Clear filters", noMatches: "No projects match your filters", noMatchesHint: "Try a broader category or clear the filters to see every open brief.", hiring: "Hiring for a project?", ctaTitle: "Post a brief & connect with verified student talent", ctaDescription: "Posting is free. Escrow keeps your funds safe until deliverables are approved.", postNow: "Post a brief now", post: "Post a project", client: "Client", general: "General", fixedPrice: "Fixed price", remote: "Remote", proposals: "{{count}} proposals", showing: "Showing {{count}} briefs matching your criteria" } },
  am: { projects: { marketplace: "የገበያ ሥራዎች", title: "ክፍት ፕሮጀክቶችን ይመልከቱ", search: "ፕሮጀክቶችን ፈልግ", searchPlaceholder: "በርዕስ፣ በክህሎት ወይም በቁልፍ ቃል ይፈልጉ...", category: "ምድብ", allCategories: "ሁሉም ምድቦች", experience: "የልምድ ደረጃ", sortBy: "ደርድር በ", clearFilters: "ማጣሪያዎችን አጽዳ", noMatches: "ምንም ፕሮጀክት ከማጣሪያዎ ጋር አይዛመድም", noMatchesHint: "ሰፋ ያለ ምድብ ይሞክሩ ወይም ማጣሪያዎቹን ያጽዱ።", hiring: "ለፕሮጀክት ሰው እየቀጠሩ ነው?", ctaTitle: "ሥራ ያቅርቡና ከተረጋገጡ ተማሪዎች ጋር ይገናኙ", ctaDescription: "ማቅረብ ነፃ ነው። ኤስክሮ የተሰጠው ሥራ እስኪጸድቅ ገንዘብዎን ይጠብቃል።", postNow: "አሁን ሥራ ያቅርቡ", post: "ፕሮጀክት ያቅርቡ", client: "ደንበኛ", general: "አጠቃላይ", fixedPrice: "ቋሚ ዋጋ", remote: "ከርቀት", proposals: "{{count}} ፕሮፖዛሎች", showing: "ከመስፈርትዎ ጋር የሚዛመዱ {{count}} ሥራዎች እየታዩ ነው" } },
  af: { projects: { marketplace: "Hojiiwwan gabaa", title: "Pirojektoota banaa ilaali", search: "Pirojektoota barbaadi", searchPlaceholder: "Mata-dureen, dandeettii ykn jecha ijoo barbaadi...", category: "Ramaddii", allCategories: "Ramaddiiwwan hunda", experience: "Sadarkaa muuxannoo", sortBy: "Akkaataan tartiibaa", clearFilters: "Calaltuu qulqulleessi", noMatches: "Pirojektiin tokko illee calaltuu kee waliin hin walsimne", noMatchesHint: "Ramaddii bal'aa yaali ykn calaltuu qulqulleessi.", hiring: "Pirojektiif hojjetaa qacaraa jirtaa?", ctaTitle: "Hojii maxxansii dandeettii barataa mirkanaa'e waliin wal qunnami", ctaDescription: "Maxxansiisuun bilisa. Eskroon hanga hojii eebbamuu maallaqa kee eega.", postNow: "Amma hojii maxxansi", post: "Pirojektii maxxansi", client: "Maamilaa", general: "Waliigalaa", fixedPrice: "Gatii dhaabbataa", remote: "Fagoo", proposals: "Pirooppoozaala {{count}}", showing: "Hojiiwwan {{count}} ulaagaalee kee waliin walsiman mul'achaa jiru" } }
};
const projectFormResources = {
  en: { projectsForm: { postTitle: "Post a project", postDescription: "Get university-verified students bidding on your brief.", basics: "Basics", skillsBudget: "Skills & budget", review: "Review", tellWork: "Tell us about the work", tellWorkHint: "A clear title and description get better proposals.", setExpectations: "Skills, budget & timeline", setExpectationsHint: "Set expectations so students can price accurately.", reviewPublish: "Review & publish", reviewPublishHint: "Check everything looks right before publishing.", title: "Project title", titlePlaceholder: "E.g. Build a React dashboard for our campus club", description: "Description", descriptionPlaceholder: "What do you need built? What does success look like?", category: "Category", chooseCategory: "Choose a category", requiredSkills: "Required skills", skillsHint: "Structured skills drive our matching engine.", chooseSkill: "Choose a skill from the catalogue", add: "Add", experience: "Experience level", currency: "Payment currency", stripe: "USD — Stripe", chapa: "ETB — Chapa", currencyHint: "This currency is locked into the contract and its milestones.", budgetType: "Budget type", fixed: "Fixed budget", range: "Budget range", minimum: "Minimum ({{currency}})", maximum: "Maximum ({{currency}})", budget: "Budget ({{currency}})", deadline: "Deadline", titleSummary: "Title", categorySummary: "Category", budgetSummary: "Budget", back: "Back", continue: "Continue", publish: "Publish project", priceUnavailable: "Not enough historical proposals for these skills yet to suggest a price.", checkingPrice: "Checking similar accepted proposals…", usePrice: "Use this", similarPrice: "Similar accepted proposals settled around", sample: "sample", projectPosted: "Project posted — students can now submit proposals", postError: "Could not post project" } },
  am: { projectsForm: { postTitle: "ፕሮጀክት ያቅርቡ", postDescription: "ከዩኒቨርሲቲ የተረጋገጡ ተማሪዎች በሥራዎ ላይ እንዲወዳደሩ ያድርጉ።", basics: "መሠረታዊ መረጃ", skillsBudget: "ክህሎቶች እና በጀት", review: "ገምግም", tellWork: "ስለ ሥራው ይንገሩን", tellWorkHint: "ግልጽ ርዕስና መግለጫ የተሻሉ ፕሮፖዛሎችን ያመጣል።", setExpectations: "ክህሎቶች፣ በጀት እና ጊዜ ሰሌዳ", setExpectationsHint: "ተማሪዎች በትክክል ዋጋ እንዲያስሉ መስፈርቶችን ያዘጋጁ።", reviewPublish: "ገምግመው ያትሙ", reviewPublishHint: "ከማተምዎ በፊት ሁሉም ነገር ትክክል መሆኑን ያረጋግጡ።", title: "የፕሮጀክት ርዕስ", titlePlaceholder: "ለምሳሌ፦ ለካምፓስ ክለባችን React dashboard ይገንቡ", description: "መግለጫ", descriptionPlaceholder: "ምን እንዲሠራ ይፈልጋሉ? ስኬት ምን ይመስላል?", category: "ምድብ", chooseCategory: "ምድብ ይምረጡ", requiredSkills: "አስፈላጊ ክህሎቶች", skillsHint: "የተደራጁ ክህሎች የተዛማጅነት ሞተራችንን ያንቀሳቅሳሉ።", chooseSkill: "ከዝርዝሩ ክህሎት ይምረጡ", add: "አክል", experience: "የልምድ ደረጃ", currency: "የክፍያ ምንዛሬ", stripe: "USD — Stripe", chapa: "ETB — Chapa", currencyHint: "ይህ ምንዛሬ በውሉና በደረጃዎቹ ውስጥ ይቆለፋል።", budgetType: "የበጀት ዓይነት", fixed: "ቋሚ በጀት", range: "የበጀት ክልል", minimum: "ዝቅተኛ ({{currency}})", maximum: "ከፍተኛ ({{currency}})", budget: "በጀት ({{currency}})", deadline: "የመጨረሻ ቀን", titleSummary: "ርዕስ", categorySummary: "ምድብ", budgetSummary: "በጀት", back: "ተመለስ", continue: "ቀጥል", publish: "ፕሮጀክት አትም", priceUnavailable: "ለእነዚህ ክህሎቶች ዋጋ ለመጠቆም በቂ የቀድሞ ፕሮፖዛል የለም።", checkingPrice: "ተመሳሳይ የተቀበሉ ፕሮፖዛሎችን በመፈተሽ ላይ…", usePrice: "ይህን ይጠቀሙ", similarPrice: "ተመሳሳይ የተቀበሉ ፕሮፖዛሎች የተዘጋጁት በዚህ አካባቢ ነው", sample: "ናሙና", projectPosted: "ፕሮጀክቱ ታትሟል — ተማሪዎች አሁን ፕሮፖዛል ማስገባት ይችላሉ", postError: "ፕሮጀክቱን ማተም አልተቻለም" } },
  af: { projectsForm: { postTitle: "Pirojektii maxxansi", postDescription: "Barattoota yuunivarsiitiin mirkanaa'an hojii kee irratti akka dorgoman taasisi.", basics: "Bu'uura", skillsBudget: "Dandeettii fi baajata", review: "Ilaali", tellWork: "Waa'ee hojii nuuf himi", tellWorkHint: "Mata-duree fi ibsi ifaan pirooppoozaala fooyya'aa fida.", setExpectations: "Dandeettii, baajata fi yeroo", setExpectationsHint: "Barattoonni gatii sirriitti akka shallagan ulaagaalee kaa'i.", reviewPublish: "Ilaalii maxxansi", reviewPublishHint: "Maxxansuu kee dura wanti hundi sirrii ta'uu mirkaneessi.", title: "Mata-duree pirojektii", titlePlaceholder: "Fkn. Kilabii kaampaasii keenyaaf dashboard React ijaari", description: "Ibsa", descriptionPlaceholder: "Maal akka ijaaramu barbaadda? Milkaa'inni maal fakkaata?", category: "Ramaddii", chooseCategory: "Ramaddii filadhu", requiredSkills: "Dandeettiiwwan barbaachisan", skillsHint: "Dandeettiiwwan qindaa'an motora walitti firooma keenyaa oofu.", chooseSkill: "Kataloogii keessaa dandeettii filadhu", add: "Dabali", experience: "Sadarkaa muuxannoo", currency: "Maallaqa kaffaltii", stripe: "USD — Stripe", chapa: "ETB — Chapa", currencyHint: "Maallaqni kun waliigaltee fi milestoona isaa keessatti cufama.", budgetType: "Gosa baajataa", fixed: "Baajata dhaabbataa", range: "Daangaa baajataa", minimum: "Xiqqaa ({{currency}})", maximum: "Guddaa ({{currency}})", budget: "Baajata ({{currency}})", deadline: "Guyyaa xumuraa", titleSummary: "Mata-duree", categorySummary: "Ramaddii", budgetSummary: "Baajata", back: "Duubatti", continue: "Itti fufi", publish: "Pirojektii maxxansi", priceUnavailable: "Dandeettiiwwan kanaaf gatii yaaduuf pirooppoozaalli seenaa gahaan hin jiru.", checkingPrice: "Pirooppoozaala walfakkaataa fudhatame qorachaa jira…", usePrice: "Kana fayyadami", similarPrice: "Pirooppoozaalli walfakkaataan fudhatame naannoo kanaatti xumurame", sample: "fakkeenya", projectPosted: "Pirojektiin maxxanfameera — barattoonni amma pirooppoozaala galchuu danda'u", postError: "Pirojektii maxxansuu hin dandeenye" } }
};
const projectDetailResources = {
  en: { projects: { verifyFirst: "Verify your university first", verifiedOnly: "Clients only see proposals from verified students. Submit your university details from your profile — most requests are reviewed within a couple of days.", getVerified: "Get verified", projectClosed: "This project is no longer accepting proposals.", submitProposal: "Submit a proposal", submitYourProposal: "Submit your proposal", proposalHint: "Clients compare price, timeline, and cover notes side by side. Be specific.", yourPrice: "Your price ({{currency}})", deliveryDays: "Delivery time (days)", coverNote: "Cover note", incomingProposals: "Incoming proposals ({{count}})", noProposals: "No proposals yet. Share this project to attract students.", universityVerified: "University verified", viewCv: "View CV", recommendedStudents: "Recommended students", recommendedHint: "Verified students whose skills best match this brief — no proposal required yet.", editProject: "Edit project", onlyOpenEditable: "Only open projects can be edited.", loadError: "Project couldn't be loaded", backToProjects: "Back to projects", allProjects: "All projects", remote: "Remote", proposals: "{{count}} proposals", brief: "The brief", skillsRequired: "Skills required", aboutClient: "About the client", budget: "Budget" } },
  am: { projects: { verifyFirst: "መጀመሪያ ዩኒቨርሲቲዎን ያረጋግጡ", verifiedOnly: "ደንበኞች ከተረጋገጡ ተማሪዎች የቀረቡ ፕሮፖዛሎችን ብቻ ያያሉ። የዩኒቨርሲቲ ዝርዝርዎን ከመገለጫዎ ያስገቡ።", getVerified: "ማረጋገጫ ያግኙ", projectClosed: "ይህ ፕሮጀክት ከእንግዲህ ፕሮፖዛል አይቀበልም።", submitProposal: "ፕሮፖዛል ያስገቡ", submitYourProposal: "ፕሮፖዛልዎን ያስገቡ", proposalHint: "ደንበኞች ዋጋን፣ ጊዜንና ማብራሪያን ያወዳድራሉ። ግልጽ ይሁኑ።", yourPrice: "የእርስዎ ዋጋ ({{currency}})", deliveryDays: "የማስረከቢያ ጊዜ (ቀናት)", coverNote: "የማብራሪያ ማስታወሻ", incomingProposals: "የገቡ ፕሮፖዛሎች ({{count}})", noProposals: "እስካሁን ፕሮፖዛል የለም። ተማሪዎችን ለመሳብ ፕሮጀክቱን ያጋሩ።", universityVerified: "ዩኒቨርሲቲ ተረጋግጧል", viewCv: "CV ይመልከቱ", recommendedStudents: "የሚመከሩ ተማሪዎች", recommendedHint: "ክህሎታቸው ከዚህ ሥራ ጋር የሚጣጣሙ የተረጋገጡ ተማሪዎች።", editProject: "ፕሮጀክት አስተካክል", onlyOpenEditable: "ክፍት ፕሮጀክቶች ብቻ ሊስተካከሉ ይችላሉ።", loadError: "ፕሮጀክቱ መጫን አልተቻለም", backToProjects: "ወደ ፕሮጀክቶች ተመለስ", allProjects: "ሁሉም ፕሮጀክቶች", remote: "ከርቀት", proposals: "{{count}} ፕሮፖዛሎች", brief: "የሥራው መግለጫ", skillsRequired: "አስፈላጊ ክህሎቶች", aboutClient: "ስለ ደንበኛው", budget: "በጀት" } },
  af: { projects: { verifyFirst: "Jalqaba yuunivarsiitii kee mirkaneessi", verifiedOnly: "Maamiltoonni pirooppoozaala barattoota mirkanaa'an irraa dhufe qofa argu. Odeeffannoo yuunivarsiitii kee profaayila kee irraa galchi.", getVerified: "Mirkaneeffami", projectClosed: "Pirojektiin kun amma pirooppoozaala hin fudhatu.", submitProposal: "Pirooppoozaala galchi", submitYourProposal: "Pirooppoozaala kee galchi", proposalHint: "Maamiltoonni gatii, yeroo fi ibsa wal bira qabu. Ifa ta'i.", yourPrice: "Gatii kee ({{currency}})", deliveryDays: "Yeroo geejjibaa (guyyoota)", coverNote: "Yaada dabalataa", incomingProposals: "Pirooppoozaala dhufan ({{count}})", noProposals: "Ammaaf pirooppoozaalli hin jiru. Barattoota hawwachuuf pirojektii kana qoodi.", universityVerified: "Yuunivarsiitiin mirkanaa'eera", viewCv: "CV ilaali", recommendedStudents: "Barattoota gorfaman", recommendedHint: "Barattoota mirkanaa'an dandeettiin isaanii hojii kana waliin sirriitti walsimu.", editProject: "Pirojektii gulaali", onlyOpenEditable: "Pirojektoonni banaa qofa gulaalamuu danda'u.", loadError: "Pirojektii fe'uu hin dandeenye", backToProjects: "Gara pirojektootaatti deebi'i", allProjects: "Pirojektoota hunda", remote: "Fagoo", proposals: "Pirooppoozaala {{count}}", brief: "Ibsa hojii", skillsRequired: "Dandeettiiwwan barbaachisan", aboutClient: "Waa'ee maamilaa", budget: "Baajata" } }
};
import {
  commonResources,
  contractsPageResources,

  proposalsPageResources,
  paymentsPageResources,
  walletsPageResources,
  disputesPageResources,
  notificationsPageResources,
  settingsPageResources,
  searchPageResources,
  clientsPageResources,
  chatPageResources,
  invoicesPageResources,
  portfoliosPageResources,
  learningPageResources,
  recommendationPageResources,
  reviewsSectionResources,
  analyticsPageResources,
  adminPageResources,
  miscPagesResources,
  landingPageResources,
} from "./moreResources.js";

const extraBundles = [
  commonResources,
  projectDetailResources,
  contractsPageResources,
  proposalsPageResources,
  paymentsPageResources,
  walletsPageResources,
  disputesPageResources,
  notificationsPageResources,
  settingsPageResources,
  searchPageResources,
  clientsPageResources,
  chatPageResources,
  invoicesPageResources,
  portfoliosPageResources,
  learningPageResources,
  recommendationPageResources,
  reviewsSectionResources,
  analyticsPageResources,
  adminPageResources,
  miscPagesResources,
  landingPageResources,
];


function mergeResources(...objs) {
  const result = {};
  for (const obj of objs) {
    if (!obj) continue;
    for (const key of Object.keys(obj)) {
      if (typeof obj[key] === "object" && obj[key] !== null && !Array.isArray(obj[key])) {
        result[key] = { ...(result[key] || {}), ...obj[key] };
      } else {
        result[key] = obj[key];
      }
    }
  }
  return result;
}

let stored = null;
try {
  stored = typeof localStorage !== "undefined" ? localStorage.getItem("nw_language") : null;
} catch {
  // Some browsers block localStorage; use the browser language instead.
}
const browser = typeof navigator !== "undefined" ? navigator.language?.split("-")[0] : null;
const initial = supported.includes(stored) ? stored : supported.includes(browser) ? browser : "en";

const initialEn = mergeResources(en, sharedResources.en, mfaResources.en, registrationResources.en, dashboardResources.en, directoryResources.en, dashboardRoleResources.en, profileResources.en, profileOverviewResources.en, profileFieldResources.en, skillsResources.en, universityResources.en, projectResources.en, projectFormResources.en);
const initialAm = mergeResources(am, sharedResources.am, mfaResources.am, registrationResources.am, dashboardResources.am, directoryResources.am, dashboardRoleResources.am, dashboardDetailsResources.am, profileResources.am, profileOverviewResources.am, profileFieldResources.am, skillsResources.am, universityResources.am, projectResources.am, projectFormResources.am);
const initialAf = mergeResources(af, sharedResources.af, mfaResources.af, registrationResources.af, dashboardResources.af, directoryResources.af, dashboardRoleResources.af, dashboardDetailsResources.af, profileResources.af, profileOverviewResources.af, profileFieldResources.af, skillsResources.af, universityResources.af, projectResources.af, projectFormResources.af);

i18n.use(initReactI18next).init({
  resources: {
    en: { translation: initialEn },
    am: { translation: initialAm },
    af: { translation: initialAf },
  },
  lng: initial,
  fallbackLng: "en",
  supportedLngs: supported,
  interpolation: { escapeValue: true },
  returnNull: false,
});

for (const bundle of extraBundles) {
  if (bundle.en) i18n.addResourceBundle("en", "translation", bundle.en, true, true);
  if (bundle.am) i18n.addResourceBundle("am", "translation", bundle.am, true, true);
  if (bundle.af) i18n.addResourceBundle("af", "translation", bundle.af, true, true);
}


i18n.on("languageChanged", (lng) => { try { if (typeof localStorage !== "undefined") localStorage.setItem("nw_language", supported.includes(lng) ? lng : "en"); } catch { /* storage is optional */ } if (typeof document !== "undefined") { document.documentElement.lang = lng; document.documentElement.dir = ["ar", "he", "fa"].includes(lng) ? "rtl" : "ltr"; translateLegacyDom(lng); } });
if (typeof document !== "undefined" && typeof MutationObserver !== "undefined") { const observer = new MutationObserver(() => translateLegacyDom(i18n.language)); observer.observe(document.documentElement, { childList: true, subtree: true }); }
if (typeof window !== "undefined") window.__nwI18n = i18n;
export { supported };
export default i18n;
