import { Router } from "express";

import { AuthRoutes } from "../../modules/auth/index.js";
import { UsersRoutes } from "../../modules/users/index.js";
import { StudentsRoutes } from "../../modules/students/index.js";
import { ClientsRoutes } from "../../modules/clients/index.js";
import { UniversitiesRoutes } from "../../modules/universities/index.js";
import { VerificationsRoutes } from "../../modules/verifications/index.js";
import { CategoriesRoutes } from "../../modules/categories/index.js";
import { SkillsRoutes } from "../../modules/skills/index.js";
import { ProjectsRoutes } from "../../modules/projects/index.js";
import { ProposalsRoutes } from "../../modules/proposals/index.js";
import { ContractsRoutes } from "../../modules/contracts/index.js";
import { MilestonesRoutes } from "../../modules/milestones/index.js";
import { SubmissionsRoutes } from "../../modules/submissions/index.js";
import { FilesRoutes } from "../../modules/files/index.js";
import { PaymentsRoutes } from "../../modules/payments/index.js";
import { WalletsRoutes } from "../../modules/wallets/index.js";
import { InvoicesRoutes } from "../../modules/invoices/index.js";
import { ReviewsRoutes } from "../../modules/reviews/index.js";
import { DisputesRoutes } from "../../modules/disputes/index.js";
import { MessagingRoutes } from "../../modules/messaging/index.js";
import { NotificationsRoutes } from "../../modules/notifications/index.js";
import { PortfoliosRoutes } from "../../modules/portfolios/index.js";
import { LearningRoutes } from "../../modules/learning/index.js";
import { SearchRoutes } from "../../modules/search/index.js";
import { RecommendationRoutes } from "../../modules/recommendation/index.js";
import { AnalyticsRoutes } from "../../modules/analytics/index.js";
import { AdminRoutes } from "../../modules/admin/index.js";
import { AuditLogsRoutes } from "../../modules/audit-logs/index.js";
import { HealthRoutes } from "../../modules/health/index.js";

const router = Router();

router.use("/auth", AuthRoutes);
router.use("/users", UsersRoutes);
router.use("/students", StudentsRoutes);
router.use("/clients", ClientsRoutes);
router.use("/universities", UniversitiesRoutes);
router.use("/verifications", VerificationsRoutes);
router.use("/categories", CategoriesRoutes);
router.use("/skills", SkillsRoutes);
router.use("/projects", ProjectsRoutes);
router.use("/proposals", ProposalsRoutes);
router.use("/contracts", ContractsRoutes);
router.use("/milestones", MilestonesRoutes);
router.use("/submissions", SubmissionsRoutes);
router.use("/files", FilesRoutes);
router.use("/payments", PaymentsRoutes);
router.use("/wallets", WalletsRoutes);
router.use("/invoices", InvoicesRoutes);
router.use("/reviews", ReviewsRoutes);
router.use("/disputes", DisputesRoutes);
router.use("/messages", MessagingRoutes);
router.use("/notifications", NotificationsRoutes);
router.use("/portfolios", PortfoliosRoutes);
router.use("/learning", LearningRoutes);
router.use("/search", SearchRoutes);
router.use("/recommendations", RecommendationRoutes);
router.use("/analytics", AnalyticsRoutes);
router.use("/admin", AdminRoutes);
router.use("/audit-logs", AuditLogsRoutes);
router.use("/health", HealthRoutes);

export default router;
